application: watsancomm
version: 1-1
runtime: python
api_version: 1

inbound_services:
  - mail

handlers:
  - url: /main/.*
    script: watsancomm.py
    login: admin
  - url: /_ah/mail/weekly@.*\.appspotmail\.com
    script: handle_weekly.py
    login: admin
  - url: /_ah/mail/weeklysummary@.*\.appspotmail\.com
    script: disregard_mail.py
    login: admin
