application: watsancomm
version: 1
runtime: python
api_version: 1

inbound_services:
  - mail

handlers:
  - url: /
    script: watsancomm.py
  - url: /_ah/mail/weekly@.*\.appspotmail\.com
    script: handle_weekly.py
    login: admin
